name: test
on: push

jobs:
  check:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Updating pre existing packages
        run: sudo apt-get update

      - name: snap check
        run: snap --version
      - name: installing and setting up aws cli
        run: 

      - name: Check out code
        uses: actions/checkout@v4
        
      - run: ls -l
      
      - name: Secret test
        env:
          secret: ${{ secrets.HELLO }}
        run: echo "$secret"

      - name: Env test
        env:
          val: ${{ vars.WHAT }}
        run: echo "$val"

      - run: ls ~

      - run: python -V

      - run: python ./.github/workflows/deploy.py > test.sh
        env:
          val: ${{secrets.HELLO}}

      # Display the content of test.sh
      - run: cat test.sh

      # Source the script and use variables it exports
      - run: |
          source ./test.sh
          echo "Value of VAR after sourcing test.sh: $VAR"
      - run: ls -la
      - run: 
