name: test
on: push

#dheiheihdei
jobs:
  check:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: installing and setting up aws cli
        run: sudo snap install aws-cli --classic

      - name: configuring aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ap-south-1
        run: |
          aws ec2 run-instances \
            --instance-type t3.micro \
            --count 1 \
            --image-id ami-0614680123427b75e
            --key-name 

      - name: Check out code
        uses: actions/checkout@v4
        
      - run: ls -l
      
      - name: Secret test
        env:
          secret: ${{ secrets.HELLO }}
        run: echo "$secret"

      - name: Env test
        env:
          val: ${{ vars.WHAT }}
        run: echo "$val"

      - run: ls ~

      - run: python -V

      - run: python ./.github/workflows/deploy.py > test.sh
        env:
          val: ${{secrets.HELLO}}

      # Display the content of test.sh
      - run: cat test.sh

      # Source the script and use variables it exports
      - run: |
          source ./test.sh
          echo "Value of VAR after sourcing test.sh: $VAR"
      - run: ls -la
