name: test
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "tests"
      - name: Check out code
        uses: actions/checkout@v4
      - run: ls -l
      - name: secret test
        env: 
          secret:${{secrets.HELLO}}
        run: echo $secret
      - name: env test
        env:
          var: {{ env.WHAT }}
        run: echo $var
